{% set name = "consolekit" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/consolekit-{{ version }}.tar.gz
  sha256: 20ec8e8e5dab4ac5d2a306c15938034f1a23d54385367d1e976c2b271204d814

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python {{ python_min }}
  run:
    - click >=7.1.2
    - colorama >=0.4.3
    - deprecation-alias >=0.1.1
    - domdf-python-tools >=3.8.0
    - mistletoe >=0.7.2
    - python >={{ python_min }}
    - typing-extensions !=3.10.0.1,>=3.10.0.0

test:
  imports:
    - consolekit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/domdfcoding/consolekit
  summary: Additional utilities for click.
  license: MIT
  license_file: LICENSE
  doc_url: https://consolekit.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - domdfcoding
